weights: yolov5s.pt
cfg: ''
data: ../dataset_data.yaml
hyp:
  lr0: 0.001
  lrf: 0.1
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  box: 0.05
  cls: 0.3
  cls_pw: 1.0
  obj: 0.5
  obj_pw: 1.0
  iou_t: 0.7
  anchor_t: 4.0
  anchors: 3
  fl_gamma: 0.0 ???
  hsv_h: 0.2
  hsv_s: 0.5      change
  hsv_v: 0.2      change
  degrees: 90     change (may be 0?)
  translate: "0.1 \u043D\u0435 \u0441\u043F\u0440\u0430\u0448\u0438\u0432\u0430\u043B"
  scale: "0.1      \u043C\u0435\u043D\u044C\u0448\u0435 \u0441\u0434\u0435\u043B\u0430\
    \u0442\u044C \u0438\u043B\u0438 \u0443\u0431\u0440\u0430\u0442\u044C"
  shear: "0.0      \u043D\u0435 \u0441\u043F\u0440\u0430\u0448\u0438\u0432\u0430\u043B"
  perspective: "0.001  \u043C\u0435\u043D\u044C\u0448\u0435 \u0438\u043B\u0438 \u0443\
    \u0431\u0440\u0430\u0442\u044C"
  flipud: 0.5
  fliplr: 0.5
  mosaic: 1
  mixup: "0.0      \u0441\u043F\u0440\u043E\u0441\u0438\u0442\u044C \u0445\u0437"
  copy_paste: 0.5
epochs: 300
batch_size: 32
imgsz: 1280
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
evolve_population: data/hyps
resume_evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs/train
name: jupyter new hyps 14_22_21_05_24
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: 1
seed: 0
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
ndjson_console: false
ndjson_file: false
save_dir: runs/train/jupyter new hyps 14_22_21_05_24
