weights: yolov5s.pt
cfg: ''
data: ../dataset_data.yaml
hyp:
  lr0: 0.001
  lrf: 0.1
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  box: 0.05
  cls: 0.3
  cls_pw: 1.0
  obj: 0.5
  obj_pw: 1.0
  iou_t: 0.7
  anchor_t: 4.0
  anchors: 3
  fl_gamma: null
  hsv_h: 0.2
  hsv_s: 0.5
  hsv_v: 0.2
  degrees: 90
  translate: 0.1
  scale: 0.1
  shear: 0.0
  perspective: 0.001
  flipud: 0.5
  fliplr: 0.5
  mosaic: 1
  mixup: 0.0
  copy_paste: 0.5
epochs: 300
batch_size: 32
imgsz: 1280
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
evolve_population: data/hyps
resume_evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs/train
name: jupyter new hyps 14_22_21_05_24
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: 1
seed: 0
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
ndjson_console: false
ndjson_file: false
save_dir: runs/train/jupyter new hyps 14_22_21_05_243
